# Generated by Django 3.1.5 on 2021-03-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
